config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  devise_for :users
  root to: 'topics#index'
  resources :topics, except: [:destroy, :new]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  has_many :comments
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  has_many :topics
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    @topics = Topic.all.reverse
    @topic = Topic.new
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def create
    p params[:topic][:question]
    @topic = Topic.new(user: current_user, question: params[:topic][:question])
    if @topic.save
      # respond_to do |format|
      #   # format.html (redirect_to topics_path)
      #   format.js
      # end
      ActionCable.server.broadcast 'topics',
        topic: @topic.question
      head :ok
    else
      respond_to do |format|
        format.html (render 'topics/index')
        format.js
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container padded">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <h1><i class="fa fa-newspaper-o"></i></h1>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-newspaper-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to t(".sign_in", default: "Login"), new_user_session_path%></li>
        <li></i>  <%= t(".sign_out", default: "Log out") %></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/topics/_form.html.erb
<%= simple_form_for(topic, remote: true) do |f| %>
  <%= f.input :question %>
  <%= f.submit "Ask", class: "btn btn-primary" %>
<% end %>

app/views/topics/_topic.html.erb
<div class="topic">
  <%= link_to topic.question, topic_path(topic) %>
  <%= " " + topic.posts.count.to_s %>
</div>

app/views/topics/create.js.erb
<% if @topic.errors.any? %>
  $('.topic_question').html("<%= j render 'topics/form', topic: @topic %>");
<% else %>
  var new_topic = $("<%= j render 'topics/topic', topic: @topic %>").hide();

  $('.topic-list').prepend(new_topic);

  new_topic.slideDown();

<% end %>

app/views/topics/index.html.erb
<%= render 'form', topic: @topic %>

<div class="topic-list">
  <% @topics.each do |topic| %>
    <%= render 'topic', topic: topic %>
  <% end %>
</div>

app/views/topics/show.html.erb
<%= link_to "< Back to questions", topics_path %>
<h2><%= @topic.question %></h2>

<% @topic.posts.each do |post| %>
  <div class="post">
    <%= post.title %>
    <%= link_to post.url, post.url %>
    <%= " " + post.comments.count.to_s %>
  </div>
<% end %>